// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCoirMgnv6NQu_wvnAUsdpkZ2Y0kg150M',
    appId: '1:946326167735:web:b8ed877eff2d681b3ded32',
    messagingSenderId: '946326167735',
    projectId: 'fruteriatrejo-ef644',
    authDomain: 'fruteriatrejo-ef644.firebaseapp.com',
    storageBucket: 'fruteriatrejo-ef644.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzfcSHZJaGY0P9It2-zVLk8pCIZYy5kbE',
    appId: '1:946326167735:android:30494330d02b69903ded32',
    messagingSenderId: '946326167735',
    projectId: 'fruteriatrejo-ef644',
    storageBucket: 'fruteriatrejo-ef644.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU-32F4EPC0bxDdaZN4XRa9_TOnOP9rgs',
    appId: '1:946326167735:ios:f35c80184676632b3ded32',
    messagingSenderId: '946326167735',
    projectId: 'fruteriatrejo-ef644',
    storageBucket: 'fruteriatrejo-ef644.firebasestorage.app',
    iosBundleId: 'com.example.ejemploia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU-32F4EPC0bxDdaZN4XRa9_TOnOP9rgs',
    appId: '1:946326167735:ios:f35c80184676632b3ded32',
    messagingSenderId: '946326167735',
    projectId: 'fruteriatrejo-ef644',
    storageBucket: 'fruteriatrejo-ef644.firebasestorage.app',
    iosBundleId: 'com.example.ejemploia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCoirMgnv6NQu_wvnAUsdpkZ2Y0kg150M',
    appId: '1:946326167735:web:fa1580e7ad4547b13ded32',
    messagingSenderId: '946326167735',
    projectId: 'fruteriatrejo-ef644',
    authDomain: 'fruteriatrejo-ef644.firebaseapp.com',
    storageBucket: 'fruteriatrejo-ef644.firebasestorage.app',
  );
}
